---
- name: install zeromq dependencies
  apt:  name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - build-essential

- command: mkdir -p {{ zeromq_source_location }}
    creates={{ zeromq_source_location }}

- name: copy zeromq tarball
  copy: src={{ zeromq_tarball }} dest={{ zeromq_source_location }}

- name: unpack zeromq source
  command: tar xf {{ zeromq_tarball }} chdir={{ zeromq_source_location }}
    creates={{ zeromq_source_path }}

- name: compile zero mq 
  command: '{{ item }} chdir={{ zeromq_source_path }}
      creates=/usr/local/lib/libzmq.so'
  with_items:
      - ./configure
      - make
      - make install
