---
- name: update repositories
  apt: update_cache=yes

- name: install basic packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - bash-completion
    - build-essential
    - vim
    - openssl
    - git
    - curl
    - htop
    - ruby-full
    - python-apt
    - sudo
    - apt-transport-https
    - lsb-release
    - ca-certificates
    - autoconf
    - libjpeg62-turbo-dbg
    - libssl-dev
    - libxml2-dev
    - libbz2-dev
    - libcurl4-openssl-dev
    - libjpeg-dev
    - libpng12-dev
    - libfreetype6-dev
    - libxml2-dev
    - libxml2-utils
    - libxslt1-dev
    - libpq-dev
    - libicu-dev
    - libreadline-dev
    - libssl-dev
    - pkg-config

- name: set the timezone
  copy: content='UTC' dest=/etc/timzone owner=root group=root mode=0644 backup=no
  notify:
    - update timezone

- name: generate the locale
  locale_gen: name=en_US.UTF-8 state=present

- name: update the locale
  command: 'update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8'

- name: update the default profile
  copy: src=.profile dest=/etc/skel/.profile

- name: add bash aliases
  copy: src=.bash_aliases dest=/etc/skel/.aliases

- name: update the default profile
  copy: src=.bash_envvars dest=/etc/skel/.envvars
