---
galaxy_info:
  author: Bright March
  description: PHP7 configured for Postgres and Redis.
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: Debian
    versions:
    - precise
  categories:
  - development
  - web

dependencies: []
