#!/usr/bin/env bash

PHPMINOR=7.3
PHPPATCH=7.3.20
PHPREDISPATCH=5.3.1
PHPINIFILE=/opt/php/$PHPMINOR/lib/php.ini

POSTGRESMINOR=11

export DEBIAN_FRONTEND=noninteractive

# Install Base Packages
apt-get install -y bash-completion build-essential vim openssl git curl htop sudo lsb-release ca-certificates unzip zip openssl ssl-cert autoconf pkg-config rsync bison
apt-get install -y libxml2 libxml2-dev libsqlite3-dev libjpeg-dev libonig-dev libicu-dev libpng-dev libpq-dev libbz2-dev libreadline-dev libzip-dev libssl-dev libcurl4 libxslt1-dev libcurl4-openssl-dev libsodium-dev libxslt-dev

# Install Redis and Postgres
apt-get install -y redis-server
apt-get install -y postgresql
apt-get install -y postgresql-client

# Configure Postgres
sed -i "s/ md5/ trust/" /etc/postgresql/$POSTGRESMINOR/main/pg_hba.conf

# Install PHP
mkdir -p "/opt/src/"
mkdir -p "/opt/php/$PHPMINOR/"

# Build PHP
cd "/opt/src/"
rm -f "/opt/src/php-$PHPPATCH.tar.gz"

wget "https://www.php.net/distributions/php-$PHPPATCH.tar.gz" -q -O "/opt/src/php-$PHPPATCH.tar.gz"
tar -xzf "/opt/src/php-$PHPPATCH.tar.gz"

cd "/opt/src/php-$PHPPATCH/"

./configure "--prefix=/opt/php/$PHPMINOR/" --disable-cgi --with-pdo-pgsql --with-zlib-dir --enable-mbstring --enable-soap --with-openssl --with-curl --with-zlib --enable-inline-optimization --with-bz2 --with-zlib --enable-sockets --enable-pcntl --enable-mbregex --enable-bcmath  --with-xmlrpc --enable-opcache --enable-intl --enable-gd --with-zip --with-jpeg --with-gettext --with-readline --enable-calendar --enable-sysvmsg --enable-sysvsem --enable-sysvshm --enable-shmop

make && make install
cp /opt/src/php-$PHPPATCH/php.ini-development $PHPINIFILE

PATH="/opt/php/$PHPMINOR/bin:$PATH"

# Build PHP Redis
cd "/opt/src/"
rm -f "/opt/src/php-redis-$PHPREDISPATCH.tgz"

wget "https://pecl.php.net/get/redis-$PHPREDISPATCH.tgz" -q -O "/opt/src/php-redis-$PHPREDISPATCH.tgz"
tar -xzf "/opt/src/php-redis-$PHPREDISPATCH.tgz"
mv "/opt/src/redis-$PHPREDISPATCH" "/opt/src/php-redis-$PHPREDISPATCH"

cd "/opt/src/php-redis-$PHPREDISPATCH/"
"/opt/php/$PHPMINOR/bin/phpize"
./configure "--with-php-config=/opt/php/$PHPMINOR/bin/php-config"

make && make install

# Configure PHP
sed -i "s/;date.timezone.*/date.timezone = UTC/" $PHPINIFILE
sed -i "s/post_max_size = .*/post_max_size = 32M/" $PHPINIFILE
sed -i "s/upload_max_filesize = .*/upload_max_filesize = 24M/" $PHPINIFILE
sed -i "s/memory_limit = .*/memory_limit = -1/" $PHPINIFILE

echo "extension=redis" >> $PHPINIFILE
echo "zend_extension=opcache" >> $PHPINIFILE

# Install Global PHP Commands
curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
wget -q http://phing.info/get/phing-latest.phar -O /usr/local/bin/phing && chmod +x /usr/local/bin/phing

curl -sS https://get.symfony.com/cli/installer | bash
mv /root/.symfony/bin/symfony /usr/local/bin/symfony
chmod +x /usr/local/bin/symfony

# User Setup
wget -q https://raw.githubusercontent.com/brightmarch/vagrant-box/master/files/.profile -O /etc/skel/.profile

cp /etc/skel/.profile /home/vagrant/.profile
chown -R vagrant:vagrant /home/vagrant/

# Cleanup
rm -rf /opt/src/*
rm -rf /opt/VBoxGuestAdditions*
apt-get -y autoremove
apt-get -y clean

find /var/cache -type f -exec rm -rf {} \;
find /var/log/ -name *.log -exec rm -f {} \;

# Add Swap Memory
/bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
chmod 0600 /var/swap.1
/sbin/mkswap /var/swap.1
/sbin/swapon /var/swap.1

# Minimize Disk Image
dd if=/dev/zero of=/EMPTY bs=1M
rm -f /EMPTY
sync
