#!/usr/bin/env bash

export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get -y upgrade

# Locale
echo "LC_ALL=en_US.UTF-8" >> /etc/default/locale
locale-gen en_US.UTF-8

# Timezone
ln -sf /usr/share/zoneinfo/UTC /etc/localtime

# Base Packages
apt-get install -y bash-completion build-essential vim openssl git curl htop python-apt sudo apt-transport-https lsb-release ca-certificates unzip

# Redis and Postgres
$POSTGRESVERSION=9.4
apt-get install -y redis-server postgresql-`$POSTGRESVERSION` postgresql-client-`$POSTGRESVERSION`

# Postgres Configuration
sed -i "s/ md5/ trust/" /etc/postgresql/`$POSTGRESVERSION`/main/pg_hba.conf

# PHP
$PHPVERSION=7.3
wget -q https://packages.sury.org/php/apt.gpg -O /etc/apt/trusted.gpg.d/php.gpg
echo "deb https://packages.sury.org/php/ jessie main" > /etc/apt/sources.list.d/php.list

apt-get update
apt-get install -y php`$PHPVERSION`-common
apt-get install -y php`$PHPVERSION`-cli
apt-get install -y php`$PHPVERSION`-json
apt-get install -y php`$PHPVERSION`-curl
apt-get install -y php`$PHPVERSION`-pgsql
apt-get install -y php`$PHPVERSION`-opcache
apt-get install -y php`$PHPVERSION`-intl
apt-get install -y php`$PHPVERSION`-xml
apt-get install -y php`$PHPVERSION`-xmlrpc
apt-get install -y php`$PHPVERSION`-redis
apt-get install -y php`$PHPVERSION`-igbinary
apt-get install -y php`$PHPVERSION`-readline
apt-get install -y php`$PHPVERSION`-mbstring
apt-get install -y php`$PHPVERSION`-zip
apt-get install -y php`$PHPVERSION`-gd
apt-get install -y php`$PHPVERSION`-bcmath
apt-get install -y php`$PHPVERSION`-soap

# PHP Configuration
sed -i "s/;date.timezone.*/date.timezone = UTC/" /etc/php/$PHPVERSION/cli/php.ini
sed -i "s/post_max_size = .*/post_max_size = 32M/" /etc/php/$PHPVERSION/cli/php.ini
sed -i "s/upload_max_filesize = .*/upload_max_filesize = 24M/" /etc/php/$PHPVERSION/cli/php.ini

# PHP Commands
curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
wget -q http://phing.info/get/phing-latest.phar -O /usr/local/bin/phing && chmod +x /usr/local/bin/phing

# User Setup
wget -q https://raw.githubusercontent.com/brightmarch/vagrant-box/master/files/.profile -O /etc/skel/.profile

cp /etc/skel/.profile /home/vagrant/.profile
chown -R vagrant:vagrant /home/vagrant/

# Cleanup
apt-get -y autoremove
apt-get -y clean

# Add Swap Memory
/bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
chmod 0600 /var/swap.1
/sbin/mkswap /var/swap.1
/sbin/swapon /var/swap.1

# Minimize The Disk Image
dd if=/dev/zero of=/EMPTY bs=1M
rm -f /EMPTY
sync
