#!/usr/bin/env bash

export DEBIAN_FRONTEND=noninteractive
VBOX_VERSION=6.1.18

# Generate Locale
locale-gen en_US.UTF-8

# Install Guest Additions
mkdir -p "/mnt/vbox"
apt-get install -y linux-headers-`uname -r` dkms

wget "https://download.virtualbox.org/virtualbox/$VBOX_VERSION/VBoxGuestAdditions_$VBOX_VERSION.iso" -O "/vagrant/VBoxGuestAdditions_$VBOX_VERSION.iso"

mount "/vagrant/VBoxGuestAdditions_$VBOX_VERSION.iso" /mnt/vbox
sh /mnt/vbox/VBoxLinuxAdditions.run
