#!/usr/bin/env bash

PHPVERSION=7.3.10
POSTGRESVERSION=10

export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get -y upgrade

# Locale
echo "LC_ALL=en_US.UTF-8" >> /etc/default/locale
locale-gen en_US.UTF-8

# Timezone
ln -sf /usr/share/zoneinfo/UTC /etc/localtime

# Base Packages
apt-get install -y bash-completion build-essential vim openssl git curl htop sudo lsb-release ca-certificates unzip zip openssl ssl-cert

# Redis and Postgres
apt-get install -y redis-server postgresql-$POSTGRESVERSION postgresql-client-$POSTGRESVERSION

# Postgres Configuration
sed -i "s/ md5/ trust/" /etc/postgresql/$POSTGRESVERSION/main/pg_hba.conf

# PHP
apt-get install -y libxml2-dev libpng-dev libpq-dev libreadline-dev libzip-dev libssl-dev libcurl4 libcurl4-openssl-dev libsodium-dev libxslt-dev

PHPDIR=/media/php
PHPFILE=php-$PHPVERSION.tar.gz
PHPINIFILE=/usr/local/lib/php.ini

mkdir $PHPDIR && cd $PHPDIR
wget https://www.php.net/distributions/$PHPFILE
tar -xzf $PHPFILE
cd php-$PHPVERSION

./configure --disable-fpm --enable-intl --enable-mbstring --with-pgsql --enable-pcntl --with-readline --enable-soap --enable-sockets --with-xmlrpc --enable-zip --with-gd --enable-bcmath --with-xmlrpc
make && make install

cp php.ini-production $PHPINIFILE

# PHP Configuration
sed -i "s/;date.timezone.*/date.timezone = UTC/" $PHPINIFILE
sed -i "s/post_max_size = .*/post_max_size = 32M/" $PHPINIFILE
sed -i "s/upload_max_filesize = .*/upload_max_filesize = 24M/" $PHPINIFILE

# PHP Commands
curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
wget -q http://phing.info/get/phing-latest.phar -O /usr/local/bin/phing && chmod +x /usr/local/bin/phing

# User Setup
wget -q https://raw.githubusercontent.com/brightmarch/vagrant-box/master/files/.profile -O /etc/skel/.profile

cp /etc/skel/.profile /home/vagrant/.profile
chown -R vagrant:vagrant /home/vagrant/

# Cleanup
apt-get -y autoremove
apt-get -y clean

# Add Swap Memory
/bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
chmod 0600 /var/swap.1
/sbin/mkswap /var/swap.1
/sbin/swapon /var/swap.1

# Minimize The Disk Image
dd if=/dev/zero of=/EMPTY bs=1M
rm -f /EMPTY
sync
