#!/usr/bin/env bash

PHPVERSION=7.3
POSTGRESVERSION=11

export DEBIAN_FRONTEND=noninteractive

# Install Base Packages
apt-get install -y bash-completion build-essential vim openssl git curl htop sudo lsb-release ca-certificates unzip zip openssl ssl-cert autoconf pkg-config
apt-get install -y libxml2 libxml2-dev libpng-dev libpq-dev libreadline-dev libzip-dev libssl-dev libcurl4 libcurl4-openssl-dev libsodium-dev libxslt-dev

# Install Redis and Postgres
apt-get install -y redis-server
apt-get install -y postgresql
apt-get install -y postgresql-client

# Configure Postgres
sed -i "s/ md5/ trust/" /etc/postgresql/$POSTGRESVERSION/main/pg_hba.conf

# Install PHP
apt-get install -y php-common php-cli php-json php-curl php-pgsql php-opcache php-intl php-xml php-xmlrpc php-redis php-igbinary php-readline php-mbstring php-zip php-gd php-bcmath php-soap

# Configure PHP
PHPINIFILE=/etc/php/$PHPVERSION/cli/php.ini

sed -i "s/error_reporting = .*/error_reporting = E_ALL/" $PHPINIFILE
sed -i "s/display_errors = .*/display_errors = On/" $PHPINIFILE
sed -i "s/;date.timezone.*/date.timezone = UTC/" $PHPINIFILE
sed -i "s/post_max_size = .*/post_max_size = 32M/" $PHPINIFILE
sed -i "s/upload_max_filesize = .*/upload_max_filesize = 24M/" $PHPINIFILE
sed -i "s/memory_limit = .*/memory_limit = 1024M/" $PHPINIFILE

# Install Global PHP Commands
curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
wget -q http://phing.info/get/phing-latest.phar -O /usr/local/bin/phing && chmod +x /usr/local/bin/phing

curl -sS https://get.symfony.com/cli/installer | bash
mv /root/.symfony/bin/symfony /usr/local/bin/symfony
chmod +x /usr/local/bin/symfony

# Install Node and NVM
su - vagrant -c ". /vagrant/provision4"

# User Setup
wget -q https://raw.githubusercontent.com/brightmarch/vagrant-box/master/files/.profile -O /etc/skel/.profile

cp /etc/skel/.profile /home/vagrant/.profile
chown -R vagrant:vagrant /home/vagrant/

# Cleanup
apt-get -y autoremove
apt-get -y clean

find /var/cache -type f -exec rm -rf {} \;
find /var/log/ -name *.log -exec rm -f {} \;

# Add Swap Memory
/bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
chmod 0600 /var/swap.1
/sbin/mkswap /var/swap.1
/sbin/swapon /var/swap.1

# Minimize Disk Image
dd if=/dev/zero of=/EMPTY bs=1M
rm -f /EMPTY
sync
