#!/usr/bin/env bash

export DEBIAN_FRONTEND=noninteractive

# Locale
echo "LC_ALL=en_US.UTF-8" >> /etc/default/locale
locale-gen en_US.UTF-8

# Timezone
ln -sf /usr/share/zoneinfo/UTC /etc/localtime

# Upgrades
apt-get update -y
apt-get upgrade -y
apt-get dist-upgrade -y
