#!/usr/bin/env bash

NODEVERSION=10.15.0
NVMDIR="`pwd`/.nvm"

# Install Node Version Manager
curl -s -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash

# Activate Node Version Manager
[ -s "$NVMDIR/nvm.sh" ] && . "$NVMDIR/nvm.sh"

# Install Node
nvm install $NODEVERSION --no-progress
nvm use --silent $NODEVERSION
