#!/usr/bin/env bash

export DEBIAN_FRONTEND=noninteractive

# Package Versions
PHPMINOR=8.0
PHPPATCH=8.0.15
PHPREDISPATCH=5.3.6
PHPINIFILE=/opt/php/$PHPMINOR/lib/php.ini

FREETYPEMINOR=2.10
FREETYPEPATCH=2.10.2

POSTGRESMINOR=11

# Install Base Packages
apt-get install -y bash-completion build-essential vim openssl git curl htop sudo lsb-release ca-certificates unzip zip openssl ssl-cert autoconf pkg-config rsync bison nginx
apt-get install -y libxml2 libxml2-dev libsqlite3-dev libjpeg-dev libonig-dev libicu-dev libpng-dev libpq-dev libbz2-dev libreadline-dev libzip-dev libssl-dev libcurl4 libxslt1-dev libcurl4-openssl-dev libsodium-dev libxslt-dev

# Install Redis and Postgres
apt-get install -y redis-server
apt-get install -y postgresql
apt-get install -y postgresql-client

# Configure Postgres
sed -i "s/ md5/ trust/" /etc/postgresql/$POSTGRESMINOR/main/pg_hba.conf

# Source Directory
mkdir -p "/opt/src/"

# Install Freetype
mkdir -p "/opt/freetype/$FREETYPEMINOR"
cd "/opt/src/"

rm -f "/opt/src/freetype-$FREETYPEPATCH.tar.gz"
rm -rf "/opt/src/freetype-$FREETYPEPATCH"

wget "https://download.savannah.gnu.org/releases/freetype/freetype-$FREETYPEPATCH.tar.gz" -q -O "/opt/src/freetype-$FREETYPEPATCH.tar.gz"
tar -xzf "/opt/src/freetype-$FREETYPEPATCH.tar.gz"

cd "/opt/src/freetype-$FREETYPEPATCH"

./configure "--prefix=/opt/freetype/$FREETYPEMINOR" --enable-freetype-config --with-bzip2=yes
make && make install

# Install PHP
mkdir -p "/opt/php/$PHPMINOR/"
cd "/opt/src/"

rm -f "/opt/src/php-$PHPPATCH.tar.gz"
rm -rf "/opt/src/php-$PHPPATCH"

wget "https://www.php.net/distributions/php-$PHPPATCH.tar.gz" -q -O "/opt/src/php-$PHPPATCH.tar.gz"
tar -xzf "/opt/src/php-$PHPPATCH.tar.gz"

cd "/opt/src/php-$PHPPATCH/"

PKG_CONFIG_PATH="/opt/freetype/$FREETYPEMINOR/lib/pkgconfig" ./configure "--prefix=/opt/php/$PHPMINOR/" --with-pdo-pgsql --with-zlib-dir --enable-mbstring --enable-soap --with-openssl --with-curl --with-zlib --with-bz2 --with-zlib --enable-sockets --enable-pcntl --enable-mbregex --enable-bcmath  --enable-opcache --enable-intl --enable-gd --with-zip --with-gettext --with-readline --enable-calendar --enable-sysvmsg --enable-sysvsem --enable-sysvshm --enable-shmop --enable-exif --enable-fpm --with-sodium --with-jpeg --with-freetype --with-fpm-user=www-data --with-fpm-group=www-data
make && make install

cp /opt/src/php-$PHPPATCH/php.ini-development $PHPINIFILE
PATH="/opt/php/$PHPMINOR/bin:$PATH"

# Build PHP Redis
cd "/opt/src/"

rm -f "/opt/src/php-redis-$PHPREDISPATCH.tgz"
rm -rf "/opt/src/php-redis-$PHPREDISPATCH"

wget "https://pecl.php.net/get/redis-$PHPREDISPATCH.tgz" -q -O "/opt/src/php-redis-$PHPREDISPATCH.tgz"
tar -xzf "/opt/src/php-redis-$PHPREDISPATCH.tgz"

mv "/opt/src/redis-$PHPREDISPATCH" "/opt/src/php-redis-$PHPREDISPATCH"
cd "/opt/src/php-redis-$PHPREDISPATCH/"

"/opt/php/$PHPMINOR/bin/phpize"
./configure "--with-php-config=/opt/php/$PHPMINOR/bin/php-config"
make && make install

# Configure PHP
sed -i "s/;date.timezone.*/date.timezone = UTC/" $PHPINIFILE
sed -i "s/post_max_size = .*/post_max_size = 48M/" $PHPINIFILE
sed -i "s/upload_max_filesize = .*/upload_max_filesize = 32M/" $PHPINIFILE
sed -i "s/memory_limit = .*/memory_limit = 256M/" $PHPINIFILE

echo "extension=redis" >> $PHPINIFILE
echo "zend_extension=opcache" >> $PHPINIFILE

# Install Global PHP Commands
curl -sS https://getcomposer.org/installer | /opt/php/$PHPMINOR/bin/php -- --install-dir=/usr/local/bin --filename=composer
wget -q http://phing.info/get/phing-latest.phar -O /usr/local/bin/phing && chmod +x /usr/local/bin/phing

curl -sS https://get.symfony.com/cli/installer | bash
mv /root/.symfony/bin/symfony /usr/local/bin/symfony
chmod +x /usr/local/bin/symfony

# User Setup
wget -q https://raw.githubusercontent.com/brightmarch/vagrant-box/master/files/.profile -O /etc/skel/.profile

cp /etc/skel/.profile /home/vagrant/.profile
chown -R vagrant:vagrant /home/vagrant/

# Cleanup
cd /
rm -rf /opt/src/*
rm -rf /opt/VBoxGuestAdditions*
apt-get -y autoremove
apt-get -y clean

find /var/cache -type f -exec rm -rf {} \;
find /var/log/ -name *.log -exec rm -f {} \;

# Add Swap Memory
/bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
chmod 0600 /var/swap.1
/sbin/mkswap /var/swap.1
/sbin/swapon /var/swap.1

# Minimize Disk Image
dd if=/dev/zero of=/EMPTY bs=1M
rm -f /EMPTY
sync
