---
- name: install postgres libraries
  apt:  name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - build-essential
    - libkrb5-dev
    - libxml2
    - libxml2-dev
    - libxslt1-dev
    - libossp-uuid-dev
    - uuid
    - python-dev
    - libreadline6
    - libreadline-dev

- name: create destination for source
  file: path={{ postgres_source_location }} state=directory

- name: copy postgres tarball
  copy: src={{ postgres_tarball }} dest={{ postgres_source_location }}

- name: unpack postgres source
  command: tar xjf {{ postgres_tarball }} chdir={{ postgres_source_location }}
    creates={{ postgres_source_path }}

- name: compile postgres 
  command: '{{ item }} chdir={{ postgres_source_path }}
      creates=/usr/local/pgsql'
  with_items:
      - ./configure --disable-debug --enable-thread-safety --with-gssapi
            --with-openssl --with-libxml --with-libxslt --with-ossp-uuid
            --with-python --without-bonjour
      - make world
      - make install
