---
- name: install postgres libraries
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - build-essential
    - libkrb5-dev
    - libxml2
    - libxml2-dev
    - libxslt1-dev
    - libossp-uuid-dev
    - uuid
    - python-dev
    - libreadline6
    - libreadline-dev

- name: create destination for source
  file: path={{ postgres_source_dir }} state=directory

- name: download postgres tarball
  get_url: url={{ postgres_source }} dest={{ postgres_source_dir }}

- name: unpack postgres source
  unarchive: src={{ postgres_source_path }} dest={{ postgres_source_dir }} copy=no
    creates={{ postgres_source_dir + postgres_dir }}

- name: compile postgres 
  command: '{{ item }} chdir={{ postgres_source_dir + postgres_dir }}
    creates=/usr/local/pgsql'
  with_items:
    - ./configure --disable-debug --enable-thread-safety --with-gssapi
        --with-openssl --with-libxml --with-libxslt --with-ossp-uuid
        --with-python --without-bonjour
    - make world
    - make install
