---
- name: download sury GPG key
  get_url: url=https://packages.sury.org/php/apt.gpg dest=/etc/apt/trusted.gpg.d/php.gpg

- name: add sury to repository list
  lineinfile: dest=/etc/apt/sources.list line="deb https://packages.sury.org/php/ jessie main"

- name: update repositories
  apt: update_cache=yes

- name: install php
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - php7.1-common
    - php7.1-json
    - php7.1-curl
    - php7.1-cli
    - php7.1-pgsql
    - php7.1-opcache
    - php7.1-intl
    - php7.1-xmlrpc
    - php7.1-redis
    - php7.1-igbinary
    - php7.1-readline

- name: set the date.timezone in php.ini
  lineinfile: dest=/etc/php/7.1/cli/php.ini line="date.timezone=UTC"

- name: set size parameters in php.ini
  lineinfile:
    dest: /etc/php/7.1/cli/php.ini
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^post_max_size = 8M", line: "post_max_size = 32M" }
    - { regexp: "^upload_max_filesize = 2M", line: "upload_max_filesize = 24M" }

- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: install phing
  shell: wget http://phing.info/get/phing-latest.phar -O /usr/local/bin/phing && chmod +x /usr/local/bin/phing
  args:
    creates: /usr/local/bin/phing
