---
- name: create destination for php-redis source
  file: path={{ php_redis_source_dir }} state=directory

- name: download php-redis tarball
  get_url: url={{ php_redis_source }} dest={{ php_redis_source_dir }}

- name: unpack php-redis source
  unarchive: src={{ php_redis_source_path }} dest={{ php_redis_source_dir }} copy=no
    creates={{ php_redis_source_dir + php_redis_dir }}

- name: install php-redis
  shell: '{{ item }} chdir={{ php_redis_source_dir + php_redis_dir }}
      creates={{ php_redis_source_dir + php_redis_dir }}/modules/redis.so'
  with_items:
    - phpize
    - ./configure
    - make && make install

- name: add the extension to php.ini
  lineinfile: dest=/usr/local/lib/php.ini line="extension=redis.so"
