---
- name: install php-ssh2 dependencies
  apt: name=libssh2-1-dev state=present

- name: create destination for php-ssh2 source
  file: path={{ php_ssh2_source_dir }} state=directory

- name: download php-ssh2 tarball
  get_url: url={{ php_ssh2_source }} dest={{ php_ssh2_source_dir }}

- name: unpack php-ssh2 source
  unarchive: src={{ php_ssh2_source_path }} dest={{ php_ssh2_source_dir }} copy=no
    creates={{ php_ssh2_source_dir + php_ssh2_dir }}

- name: compile php-ssh2
  shell: '{{ item }} chdir={{ php_ssh2_source_dir + php_ssh2_dir }}
      creates={{ php_ssh2_source_dir + php_ssh2_dir }}/modules/ssh2.so'
  with_items:
    - phpize
    - ./configure
    - make && make install

- name: add the extension to php.ini
  lineinfile: dest=/usr/local/lib/php.ini line="extension=ssh2.so"
