---
- name: install sass
  gem: name=sass version={{ sass_version }} user_install=no

- name: install compass
  gem: name=compass version={{ compass_version }} user_install=no

- name: install zurb foundation
  gem: name=zurb-foundation version={{ zurb_foundation_version }} user_install=no

- name: install god
  gem: name=god version={{ god_version }} user_install=no
