---
galaxy_info:
  author: Bright March
  description: PHP configured for Postgres. Includes SSH2, Imagick, Redis, 
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - precise
  categories:
  - development
  - web
dependencies: []
  
