---
galaxy_info:
  author: Bright March
  description: Node installation.
  license: MIT
  min_ansible_version: 1.8
  platforms:
  - name: Ubuntu
    versions:
    - precise
  categories:
  - development
     
dependencies: []
