#!/bin/sh

### BEGIN INIT INFO
# Provides:             postgres
# Required-Start:       $all
# Required-Stop:        $all
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    PostgreSQL Server
### END INIT INFO

# Original author: Ryan Kirkpatrick <pgsql@rkirkpat.net>
# Modified author: Vic Cherubini <vcherubini@leftnode.com>

# Installation PREFIX
PREFIX=/usr/local/pgsql

# Data directory
PGDATA="/home/postgres/cluster"

# Who to run the postmaster as, usually "postgres". (NOT "root")
PGUSER=postgres

# Where to keep a log file
PGLOG="$PGDATA/pgsql.log"

# The path that is to be used for the script
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# What to use to start up the postmaster. (If you want the script to wait
# until the server has started, you could use "pg_ctl start -w" here.
# But without -w, pg_ctl adds no value.)
DAEMON="$PREFIX/bin/pg_ctl start -w"

# What to use to shut down the postmaster
PGCTL="$PREFIX/bin/pg_ctl"

set -e

# Only start if we can find the postmaster.
test -x $PGCTL || exit 1

# Parse command line parameters.
case $1 in
    start)
        echo -n "Starting PostgreSQL: "
        su - $PGUSER -c "$DAEMON -D '$PGDATA' &" >>$PGLOG 2>&1
        echo "Started"
        ;;
    stop)
        echo -n "Stopping PostgreSQL: "
        su - $PGUSER -c "$PGCTL stop -D '$PGDATA' -s -m fast"
        echo "Stopped"
        ;;
    restart)
        echo -n "Restarting PostgreSQL: "
        su - $PGUSER -c "$PGCTL stop -D '$PGDATA' -s -m fast -w"
        su - $PGUSER -c "$DAEMON -D '$PGDATA' &" >>$PGLOG 2>&1
        echo "Restarted"
        ;;
    reload)
        echo -n "Reload PostgreSQL: "
        su - $PGUSER -c "$PGCTL reload -D '$PGDATA' -s"
        echo "Reloaded"
        ;;
    status)
        su - $PGUSER -c "$PGCTL status -D '$PGDATA'"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|status}" 1>&2
        exit 1
        ;;
esac

exit 0
