---
- name: download node installer
  shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

- name: update repositories
  apt: update_cache=yes

- name: install node
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - nodejs
